name: Java CI with Maven

on:
  push:
    branches: [ master, dev, feature ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Deploy to QA
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      run: echo "QA"
    - name: Deploy to Production
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: echo "PROD"